do_dog_expression/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('imgupload.urls')),
    path('', include('single_pages.urls')),
    path('image_upload/', include('imgupload.urls')),
    path('image_upload/dog_image/process', include('imgupload.urls1')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imgupload/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from . import views

urlpatterns = [
    path('image_upload/', views.dog_image_view),
    path('success/', views.success),
    path('dog_image/', views.display_dog_images),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

single_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing),
]

imgupload/models.py
from django.db import models

# Create your models here.
class Photo(models.Model):
    name = models.CharField(max_length=50)
    dog_image = models.ImageField(upload_to='images/')

single_pages/models.py
from django.db import models

# Create your models here.

imgupload/forms.py
from django import forms
from .models import *

class ImgForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['name', 'dog_image']

imgupload/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import *


# Create your views here.
def dog_image_view(request):
    if request.method == 'POST':
        form = ImgForm(request.POST, request.FILES)

        if form.is_valid():
            form.save() # 저장
            return redirect('dog_image/') #/image_upload/dog_image/ 경로로 이동
    else:
        form = ImgForm()
    return render(request, 'dog_image_form.html', {'form': form}) #초기 등록화면. 사진 업로드 버튼

def display_dog_images(request):
    if request.method == 'GET':
        Dog = Photo.objects.all().order_by('-id')[:1] #가장 최근에 저장된 사진

        return render(request, 'display_dog_images.html', {'dog_images': Dog}) #현재 표정 등록된 화면. 분석하기 버튼

def success(request):
    return HttpResponse('successfully uploaded')

def process(request):
    #이미지 불러와서 감정 분석 처리하기
    #https://heannim-world.tistory.com/39 참고해서 진행

    #return render(request, 'dog_image_form.html', {'form': form})
    return render(request, "process_result.html") #처리 후 결과 화면 파일
          #        {'file_name': file_name, 'y_predict': y_predict, 'category': category})
                    # process_result.html에 활용할 변수 저장.

single_pages/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
    return render(
        request,
        'single_pages/landing.html'
    )

imgupload/templates/display_dog_images.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>dog image</title>
</head>
<body>
{% block content %}

    {% for dog in dog_images %}
        <!-- 가운데 정렬 완료 -->
        <h1 align="center"> {{ dog.name }} </h1>

        <!-- 사이즈 조절, 모양 만들기 및 가운데 정렬 필요 -->
        <div><img src="{{ dog.dog_image.url }}" class="img-responsive" style="width: 30%; margin-left: 35%;" /></div>
    {% endfor %}

<div align="center"><a href="process"><input type="button" value="분석하기 -> "></a></div>


    <!-- 이미지 파일 처리하는 과정으로 전환. View.py 활용 -->
{% endblock %}

</body>
</html>

imgupload/templates/dog_image_form.html
<!DOCTYPE html>
<html lang="ko">
<style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap');

    body 
    {
        font-family: 'Noto Sans KR', sans-serif;
    }

    .nav
    {
        font-weight: lighter;
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 130%;

        position : absolute;
        left:50%;
        top:50%;
        transform: translate(-50%, -820%);
        color : white
    }
    .dogname
    {
        border: 3px solid #ffc107;
        border-radius: 5px;
        height: 30px;
        width : 300px;
        font-size: 12pt;
        text-align: center;
        color: 	#6a6a6a;

        width: 250px;
        height : 30px;
        position : absolute;
        left:50%;
        top:50%;

        transform: translate(-50%, 300%);
    }

    input[type="file"]
    {
        display : none;
    }

    .dogpic
    {
        color: rgb(0, 0, 0);
        height: 230px;
        width: 230px;
        background-color: white;
        background-image: url('https://us.123rf.com/450wm/vectorv/vectorv1906/vectorv190624159/125391128-%EB%B8%94%EB%9E%99-%EC%82%AC%EC%A7%84-%EC%B9%B4%EB%A9%94%EB%9D%BC-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%9D%B0%EC%83%89-%EB%B0%B0%EA%B2%BD%EC%97%90-%EA%B3%A0%EB%A6%BD%EC%9E%85%EB%8B%88%EB%8B%A4-%EC%82%AC%EC%A7%84-%EC%B9%B4%EB%A9%94%EB%9D%BC-%EC%95%84%EC%9D%B4%EC%BD%98%EC%9E%85%EB%8B%88%EB%8B%A4-%EB%B2%A1%ED%84%B0-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%A0%88%EC%9D%B4-%EC%85%98.jpg?ver=6');
        position: absolute;
        margin: auto;
        top: 0;
        bottom: 110px;
        left: 0;
        right: 0;
        font-size: 20px;
        text-align: center;
        line-height: 390px;
        justify-items: center;
        border-radius: 50%;
        border-style: solid;
        border-width: 4px;
        border-color: #ffc107;
        background-repeat:no-repeat;
        background-position:center -25px;
        background-size: 105% 105%;
    }
    button 
    {
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        
        background: var(--button-bg-color);
        color: var(--button-color);
        
        margin: 0;
        padding: 0.5rem 1rem;
        
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 1rem;
        font-weight: 400;
        text-align: center;
        text-decoration: none;
        
        border: none;
        border-radius: 4px;
        
        display: inline-block;
        width: auto;
    }

    button.register 
    {
        --button-color: #212529;
        --button-bg-color: #ffc107;
        --button-hover-bg-color: #e0a800;
    }
    .register
    {
        width: 120px;
        height : 40px;
        position : absolute;
        left:50%;
        top:50%;

        margin : 160px -60px;
    }
</style>
<head>
    <meta charset="UTF-8">
    <title>강아지 감정 분석</title>
</head>
<body bgcolor='#666666'>
    <form method = "post" enctype="multipart/form-data">
        <input type="hidden" name="csrfmiddlewaretoken" value="uzsrA6qxqPfXApi4UhegtWC2aZu8QpXFrybmnL4ku7TDQRHLQ704H3fLdWA4ybsG">
        <div class='nav'>
            반려견 정보를 입력해주세요
        </div>
        <div class='dogname'>
            <label for="id_name"></label> 
            <input type="text" name="name" placeholder="반려견 이름을 입력하세요" required id="id_name">
        </div>
        <div class='dogpic'>
            <label for="id_dog_image">반려견 사진</label> 
            <input type="file" name="dog_image" accept="image/*" required id="id_dog_image">
        </div>
        <button class="register" type="submit">등록하기-></button>
    </form>
</body>
</html>

imgupload/templates/process_result.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>분석 결과</title>
</head>
<body>
 <h1 align="center"> 현재 강아지의 기분은? </h1>
<!--처리결과 이미지 삽입-->
<!-- 이미지 링크 걸기 -->
<!--    <img src="">    -->

<!-- html, css로 기존 기획한 페이지처럼 구성. 수정 전에는 이 부분을 지우고 서버 실행시키기 -->
<!-- {% if  %}  처리 결과가 레이블이 무표정일 경우 -->
<!--     <p>저는 지금 그냥 그래요 ૮ ・ﻌ・ა</p> 문구 예쁘게 다듬기 -->
<!-- {% elif %}  처리 결과가 레이블이 기쁨일 경우 -->
<!--     <p>저는 지금 기뻐요 ๑'ٮ'๑</p>  -->
<!-- {% elif %}  처리 결과가 레이블이 화남/위협일 경우 -->
<!--     <p>저는 지금 화나요 ٩(๑`ȏ´๑)۶</p>  -->
<!-- {% else %}  -->
<!--     <p>지금 기분을 잘 모르겠어요</p> -->
<!-- {% endif %} -->

</body>
</html>

single_pages/templates/single_pages/landing.html
<!-- 메인화면 -->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>강아지 표정 분석기</title>
</head>
<body>
<div align="center"><h1>강아지 표정 분석기</h1>
<h2>강아지가 무슨 생각을 하고 있나 알아봅시다</h2>
<a href="image_upload"><input type="button" value="시작하기 -> "></a></div>
</body>
</html>